language: ruby
before_install:
  # Bundler version issue
  # See https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler
script: bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: deploy
  target_branch: master
  keep_history: true
  local_dir: _site

# Repository settings
branches:
  except:
  - master

# Misc
notifications:
  email:
    on_success: never
