language: ruby
before_install:
  - gem update --system
  - gem install bundler
script: bundle exec jekyll build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: deploy
  target_branch: master
  keep_history: true
  local_dir: _site
